# Generated by Django 4.0.4 on 2023-02-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_orderitem_subtotal_alter_product_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_items',
        ),
    ]
